### ISSUE TITLE
【求助】Centos7出现运行错误

### ISSUE THREAD

**Issue by wu5bocheng** [zhang570221322/autoClock#10]
运行node autoDiDi.js后，错误代码
> # node autoDiDi.js
```
# node autoDiDi.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/autoDiDi.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by wllzhang** [comment]
需要先进入到autoClock目录
```bash
cd autoClock
node autoDiDi.js
```

**Comment by wu5bocheng** [comment]
好的，谢谢学长
